apiVersion: v1
kind: Pod
metadata:
  name: mydb-pod
  namespace: mydb
  labels:
    name: mydb-pod
    app: mysql
spec:
  containers:
  - name: mysql
    image: 683155782533.dkr.ecr.us-east-1.amazonaws.com/db_colorapp
    ports:
    - containerPort: 3306
    env:
    - name: MYSQL_ROOT_PASSWORD
      value: "password"