apiVersion: v1
kind: Pod
metadata:
  name: webapp-pod
  namespace: myapp
  labels:
    name: webapp
    app: employees
  annotations:
    custom.dbport: "3306"
spec:
  containers:
  - name: colorapp
    image: 683155782533.dkr.ecr.us-east-1.amazonaws.com/colorapp
    ports:
    - containerPort: 80
    env:
    - name: MYSQL_ROOT_PASSWORD
      value: "password"
    - name: DBHOST
      value: "mysql-service.mydb.svc.cluster.local"
    - name: DBPORT
      value: "3306"
